#!/bin/bash -xe

export PATH="/usr/share/rbenv/versions/2.1.2-github/bin:$PATH"

ruby -v

bundle --local --path vendor/gems/

(
    cd activerecord
    cp test/config.example.yml test/config.yml
    bundle exec rake mysql:rebuild_databases
)

bundle exec rake test
